[window]
opacity = 0.7
decorations = "none"

[window.padding]
x = 15
y = 15

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[colors.primary]
background = "#292D3B"
foreground = "#D8DEE9"

[colors.cursor]
text = "#292D3B"
cursor = "#D8DEE9"

[colors.selection]
text = "#292D3B"
background = "#D8DEE9"

[cursor.style]
shape = "Beam"
blinking = "On"

[scrolling]
history = 5000
multiplier = 3
